version: '3.5'

services:
  ttrss:
    build: .
    container_name: ttrss
    depends_on:
      ttrss-db:
        condition: service_healthy
    environment:
      DB_TYPE: pgsql
      DB_HOST: ttrss-db
      DB_PORT: 5432
      DB_NAME: ttrss
      DB_USER: ttrss
      DB_PASS: ttrss
      DB_ENV_USER: postgres
      DB_ENV_PASS: postgres
      TTRSS_SELF_URL: https://localhost
      TTRSS_WITH_SELFSIGNED_CERT: 1
      HTTP_BASIC_AUTH_USER: foo
      HTTP_BASIC_AUTH_PW: bar
    restart: unless-stopped
    ports:
      - 443:4443
    networks:
      - intern

  ttrss-db:
    image: postgres:11
    container_name: ttrss-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ttrss-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - intern

networks:
  intern:

volumes:
  ttrss-db-data:

# vim:ts=2 sw=2 et
