version: '3.5'

services:
  main:
    build: .
    links:
      - postgres:postgres
    environment:
      DB_TYPE: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ttrss
      DB_USER: ttrss
      DB_PASS: ttrss
      DB_ENV_USER: postgres
      DB_ENV_PASS: postgres
      TTRSS_SELF_URL: https://localhost
      TTRSS_WITH_SELFSIGNED_CERT: 1
    restart: unless-stopped
    ports:
      - 443:4443
    networks:
      - intern

  postgres:
    image: postgres:9.3
    volumes:
      - ./test/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - intern

networks:
  intern:

# vim:ts=2 sw=2 et